apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app 
        image: sarvjot/cpu-consuming:prod
        resources:
          requests:
            memory: "64Mi"
            cpu: "1000m"
          limits:
            memory: "128Mi"
            cpu: "1000m"
        env:
        - name: MONGODB_HOST 
          valueFrom: 
            configMapKeyRef:
              name: cpu-consuming-config
              key: MONGODB_HOST
        - name: DB
          valueFrom: 
            configMapKeyRef:
              name: cpu-consuming-config
              key: DB 
